from enum import IntEnum

class AckStatus(IntEnum):
    """
    AckStatus for various status codes used in the game server.
    """
    SUCCESS = 0
    LOGIN_USER_NOT_FOUND = 1
    LOGIN_PASSWORD_MISMATCH = 2
    LOGIN_INVALID_FORMAT = 3
    REGISTER_USER_ALREADY_EXISTS = 1
    REGISTER_INVALID_FORMAT = 2
    ROOMLIST_INVALID_INPUT = 1
    CR_INVALID_ROOM_NAME = 1
    CR_ROOM_ALREADY_EXISTS = 2
    CR_MAX_ROOM_CAP = 3
    CR_INVALID_CREATE_FORMAT = 4
    JOIN_INVALID_FORMAT = 3
    JOIN_ROOM_DNE = 1
    JOIN_ROOM_FULL = 2
    GAMEEND_BOARDSTATUS_WINNER = 0
    GAMEEND_BOARDSTATUS_DRAW = 1
    GAMEEND_BOARDSTATUS_FORFEIT = 2
